
services:
  database:
    image: mysql:8.0
    platform: linux/amd64
    container_name: fourstars-mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: four_stars_english
      MYSQL_USER: 123456
      MYSQL_PASSWORD: 123456
    ports:
      - "13306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init-db:/docker-entrypoint-initdb.d
    networks:
      - app-network
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h localhost -u root -p123456" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
  redis:
    image: redis:latest
    container_name: fourstars-redis
    networks:
      - app-network
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3-management
    container_name: fourstars-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    ports:
      - "15672:15672"
    networks:
      - app-network
    restart: unless-stopped

  nlp-api:
    container_name: fourstars-nlp-api
    build: ../AI
    ports:
      - "8000:8000"
    networks:
      - app-network
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
    restart: unless-stopped

  app:
    build: .
    container_name: fourstars-app
    depends_on:
      database:
        condition: service_healthy
      redis:
        condition: service_started
      rabbitmq:
        condition: service_started
      nlp-api:
        condition: service_started
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - TZ=Asia/Ho_Chi_Minh
      - SPRING_DATASOURCE_URL=jdbc:mysql://database:3306/four_stars_english?useSSL=false
      - SPRING_DATASOURCE_USERNAME=${DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - FOURSTARS_JWT_BASE64_SECRET=${JWT_SECRET}
      - FOURSTARS_JWT_ACCESS_TOKEN_VALIDITY_IN_SECONDS=86400
      - FOURSTARS_JWT_REFRESH_TOKEN_VALIDITY_IN_SECONDS=604800
      - FOURSTARS_UPLOAD_DIR=/app/uploads/
      - VNPAY_TMN_CODE=${VNPAY_TMN_CODE}
      - VNPAY_HASH_SECRET=${VNPAY_HASH_SECRET}
      - VNPAY_URL=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
      - VNPAY_RETURN_URL=${APP_FRONTEND_URL}/api/v1/payments/vnpay/return
      - VNPAY_IPN_URL=${APP_BACKEND_URL}/api/v1/payments/vnpay/ipn
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_USERNAME=${RABBITMQ_USER}
      - SPRING_RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
      - NLP_API_URL=${NLP_API_URL}
      - MYAPP_SCHEDULING_REMINDERS_CRON=0 0 8 * * *
      - SPRING_MAIL_USERNAME=${GMAIL_USERNAME}
      - SPRING_MAIL_PASSWORD=${GMAIL_APP_PASSWORD}
      - SPRING_MAIL_HOST=${GMAIL_HOST}
      - SPRING_MAIL_PORT=${GMAIL_PORT}
      - SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH=${GMAIL_PROPERTIES_AUTH}
      - SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE=${GMAIL_PROPERTIES_STARTTLS}
      - SPRING_MAIL_PROTOCOL=smtp
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.MySQLDialect
      - MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE=*
      - LOGGING_FILE_NAME=/app/logs/spring-app.log
      - LOGGING_PATTERN_FILE=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n
    volumes:
      - ./uploads:/app/uploads
      - ./src:/app/src
      - ./pom.xml:/app/pom.xml
      - ./logs:/app/logs
    networks:
      - app-network
    restart: unless-stopped

volumes:
  mysql-data:


networks:
  app-network:
    driver: bridge
